### ISSUE TITLE
Issue: feature request

### ISSUE THREAD

**Issue by McCroww** [HU-TI-DEV/TI-S2#116]
Met betrekking tot https://github.com/HU-TI-DEV/TI-S2/tree/main/software/c%2B%2B/oop-concepten/operatoren

Er was geen duidelijke link naar de uitleg naar meer-operatoren.md vanuit de opdracht. 
Graag een link naar meer-operatoren.md in readme.md.

**Comment by iseetea** [comment]
Meer-operatoren link toegevoegd aan inhoudsopgave. Zie: #b3abea55810327423443f4a8b09b400f85372846
