### ISSUE TITLE
Tasks.json voor sfml

### ISSUE THREAD

**Issue by K516k** [HU-TI-DEV/TI-S2#117]
mijn tasks.json werkte pas toen ik het heb aangepast naar dit:
"args": [
                "-fdiagnostics-color=always",
                "-LC:\\msys64\\mingw64\\lib",
                "${fileDirname}\\*.cpp",
                "-lsfml-graphics",
                "-lsfml-system",
                "-lsfml-window",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ]

**Comment by iseetea** [comment]
Verwerkt in opdr_rechthoek.md. Dank Koen.
