### ISSUE TITLE
Issue: wrong text Catch2

### ISSUE THREAD

**Issue by McCroww** [HU-TI-DEV/TI-S2#119]
Met betrekking tot [Catch2](https://github.com/HU-TI-DEV/TI-S2/blob/main/software/c%2B%2B/oop-concepten/unit-tests/opdr_catch2.md)

Tijdens het testen en nalopen van de code voor de eerste Catch2 opdracht kwam ik erachter dat er geen fouten in de code staan. 
Dit wordt **wel** aangegeven in de opdracht.

**Comment by iseetea** [comment]
Is opgelost. Dank!
