### ISSUE TITLE
Nog een Tasks.json voor SFML

### ISSUE THREAD

**Issue by toob01** [HU-TI-DEV/TI-S2#129]
Natuurlijk werkte geen enkele andere `tasks.json` op mijn pc, dus heb ik mn eigen aanpassingen gemaakt tot het wel goed werkte.
Na de aanwijzingen van @Lia3439 op te volgen ([zie opdr-rechthoek.md](https://github.com/HU-TI-DEV/TI-S2/blob/main/software/c%2B%2B/oop-concepten/klassen/opdr_rechthoek.md#opdracht-oo151-sfml-window)) in de MSYS2 terminal heb ik simpelweg onderstaande task in tasks.json gezet.
Het is een beetje meh, maar als het goed is kan je nu simpelweg de build task runnen via `Terminal -> Run Build Task` of de shortcut `Ctrl + Shift + B` gebruiken. De task compilet de binary, en runt die gelijk daarna, niet nodig om die zelf nog te runnen.

```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: SFML g++.exe build AND RUN active file",
            "command": "C:\\msys64\\ucrt64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${fileDirname}\\*.cpp",
		"-lsfml-graphics",
                "-lsfml-window",
                "-lsfml-system",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "&&",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\msys64\\ucrt64\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

![SFML_S2_Gif](https://github.com/HU-TI-DEV/TI-S2/assets/54207299/5a481699-27ff-46b2-a17a-ad52c087fc25)

**Comment by iseetea** [comment]
Dank Tobias!
