### ISSUE TITLE
multiple cpp files

### ISSUE THREAD

**Issue by Aimane0** [HU-TI-DEV/TI-S2#89]
${workspaceFolder}/*cpp werkt niet als je meerdere mapjes aan hebt gemaakt in je workspace folder.

"${fileDirname}\\*.cpp" is een beter alternatief als al je .cpp en .hpp files in 1 map staan

**Comment by iseetea** [comment]
Dank. Opgelost in commit ff7c147, 
zie software/c++/meerdere-bronbestanden/opdr_TV_sensatie.md
