### ISSUE TITLE
Code Correctie opdracht OO1.2

### ISSUE THREAD

**Issue by McCroww** [HU-TI-DEV/TI-S2#96]
Met betrekking tot: https://github.com/HU-TI-DEV/TI-S2/blob/main/software/c%2B%2B/oop-concepten/klassen/opdr_boeken.md#opdracht-oo12-boeken

Na het uitvoeren van de code van C++ opdracht OO1.3 kreeg ik twee foutmeldingen. Dit heb ik gedaan om de foutmelding te fixen:
1) In boek.hpp: class book>private: fix aanpassing string naar std::string
2) In boek.cpp: aanpassing include ostream naar include iostream

**Comment by iseetea** [comment]
Dank je wel. Als het goed is, is dit nu opgelost in #111.
