### ISSUE TITLE
Mogelijk ander antwoord extra oefenopgaven iets uitrekenen

### ISSUE THREAD

**Issue by McCroww** [HU-TI-DEV/TI-S2#97]
link document: https://github.com/HU-TI-DEV/TI-S2/blob/main/hardware-interfacing/basis-elektronica/iets-uitrekenen/extra-oefenopgaven-iets-uitrekenen-antwoorden.md

Bij opgave 7d, als antwoord staat er de breuk:
$\Large \frac{3(x + 2)}{- 2(x + 3) - 2}\normalsize  + a = - b$

-\> $x = \Large \frac{8b + 8a - 6}{3 - 2b - 2a}\normalsize $ 

Ik kwam zelf uit op (zie de noemer):
$\Large \frac{3(x + 2)}{- 2(x + 3) - 2}\normalsize  + a = - b$

-\> $x = \Large \frac{8b + 8a - 6}{3 - 2b + 2a}\normalsize $

![20240408_105856](https://github.com/HU-TI-DEV/TI-S2/assets/144677893/6d497f97-61c7-4b2e-a36e-9999eb261f04)

**Comment by hagen-git** [comment]
De stap van $3x - x (2b+2a)$ moet zijn $x (3 - 2b -2a)$.

Jouw stap tot $x (3 -2b +2a)$ is fout, dat zie je beter als je het schrijf als $x (3 - 1 \bullet (2b+2a))$, het minus geldt voor alle onderdelen in haakjes.

**Comment by TheMave** [comment]
@McCroww : bedankt voor de vraag.
@hagen-git : bedankt voor het beantwoorden.
