### ISSUE TITLE
Verkeerde hyperlink in readme basis-elektronica

### ISSUE THREAD

**Issue by hlwalZ** [HU-TI-DEV/TI-S2#98]
In het pad hardware-interfacing/basis-elektronica/README.md bij de introductie staat er een hyperlink "calculations with untis" die je doorstuurt naar (https://github.com/HU-TI-DEV/TI-S2/blob/main/hardware-interfacing/basis-elektronica/rekenen-met-eenheden.md)

Maar ergens zijn de bestanden ooit door elkaar gehusseld waardoor nu het juiste pad hoort te zijn:
hardware-interfacing/basis-elektronica/rekenen-met-eenheden/rekenen-met-eenheden.md

Om het te fixen verander de hyperlink naar: (https://github.com/HU-TI-DEV/TI-S2/blob/main/hardware-interfacing/basis-elektronica/rekenen-met-eenheden/rekenen-met-eenheden.md)
Groetjes van Open-ICT😋

**Comment by hlwalZ** [comment]
Regel twee onder het kopje voltage bevat ook een fout:

"You can imagine voltage (depicted by the letter U) as the pressure difference on the charged particles that will cause them to flow from a place with a high pressure to a place with a lower pressure."

De correcte letters is natuurlijk de letter V.

**Comment by Druyv** [comment]
Nee hoor, internationaal is U het meest gebruikte symbool voor voltage: https://nl.m.wikipedia.org/wiki/Elektrische_spanning

**Comment by hlwalZ** [comment]
Ik wilde hier net naartoe komen om het te verwijderen😂

**Comment by TheMave** [comment]
Top, ik heb de link gefixed. Dank je, hlwalZ!
